# -*- coding: utf-8 -*-
"""FOUNDATION_UNIT-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CUcO507xeIgp4DpZyuVyntqkBIU7-liM
"""

import math

# Given parameters
B = 1.8  # m
D = 0.8  # m
gamma = 16  # kN/m^3
phi = 30  # degrees
Nc = 30.14
Nq = 18.40
Ngamma = 15.10

# Calculate the bearing capacity
q_ult = gamma * D * Nc + 0.5 * gamma * B * Nq + gamma * Ngamma * (1 + 0.33 * phi / 5)
q_all = q_ult / 2.5

# Calculate the total load that can be carried by the footing
Q_all = q_all * B**2

# Print the results
print("Bearing capacity:", q_ult, "kN/m^2")
print("Total load that can be carried by the footing:", Q_all, "kN")