# -*- coding: utf-8 -*-
"""FOUNDATION_UNIT-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jU8evb3bxvQyyAsFasTDzn4_jVQGrkhu
"""

import math

# Given parameters
D = 0.6  # m
L = 7  # m
phi = 30  # degrees
gamma = 17  # kN/m^3
c = 20  # kN/m^2
alpha = 0.5
N = 65
Nq = 35
Ny = 18
FoS = 3

# Calculate the area of the pile
A = math.pi * (D / 2)**2

# Calculate the side resistance of the pile
Q_s = alpha * c * L * D

# Calculate the end bearing resistance of the pile
Q_b = (Nq * gamma * D * L) + (Ny * gamma * D * L)

# Calculate the total capacity of the pile
Q_t = Q_s + Q_b

# Calculate the allowable load of the pile
Q_all = Q_t / FoS

# Print the results
print("Area of the pile:", A, "m^2")
print("Side resistance of the pile:", Q_s, "kN")
print("End bearing resistance of the pile:", Q_b, "kN")
print("Total capacity of the pile:", Q_t, "kN")
print("Allowable load of the pile:", Q_all, "kN")