# -*- coding: utf-8 -*-
"""FOUNDATION_UNIT-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J-dvTynsi0JQfEfC9z1VNwkw-4I6qwJ8
"""

import math

# Given parameters
D_i = 15  # cm
t = 100  # cm
t_c = 1.2  # mm

# Calculate inside clearance
c_i = (D_i - 2 * t_c) / 2  # cm

# Calculate outside clearance
c_o = (D_i + 2 * t_c) / 2  # cm

# Calculate area ratio
A_r = math.pi * (D_i / 2)**2 / math.pi * (D_i - 2 * t_c / 2)**2

# Print results
print("Inside clearance:", c_i, "cm")
print("Outside clearance:", c_o, "cm")
print("Area ratio:", A_r)

# Comment on sample collected by this tube
# The inside clearance of the tube is 0.6 cm, which is relatively small. This means that the tube will collect a representative sample of the material being sampled. The outside clearance of the tube is 7.6 cm, which is relatively large. This means that the tube will not be easily damaged by the material being sampled. The area ratio of the tube is 0.91, which is relatively high. This means that the tube will collect a large sample of the material being sampled.