# -*- coding: utf-8 -*-
"""FOUNDATION_UNIT-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hl-zqe-wNhl-Ds6YwkdoaIVLbSSIl-9S
"""

import math

# Given parameters
H = 5  # m
e0 = 1.50
e1 = 1.44
p = 120  # kN/m^2

# Calculate the coefficient of volume compressibility
mv = (e0 - e1) / p

# Calculate the final settlement of stratum
S = mv * H * p

# Print the results
print("Coefficient of volume compressibility:", mv, "m^2/kN")
print("Final settlement of stratum:", S, "m")