# -*- coding: utf-8 -*-
"""FOUNDATION_UNIT-6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R7eSIVbbtQul2vPeY1s-rmON5xDRztBI
"""

def free_swell_index(volume_difference, initial_volume):
  """Calculates the free swell index of a soil.

  Args:
    volume_difference: The difference in volume between the swollen and unswollen soil samples in cubic centimeters.
    initial_volume: The initial volume of the unswollen soil sample in cubic centimeters.

  Returns:
    The free swell index of the soil as a percentage.
  """

  free_swell_index = (volume_difference / initial_volume) * 100

  return free_swell_index


# Example usage:

unswollen_volume = 100
swollen_volume = 150

free_swell_index = free_swell_index(swollen_volume - unswollen_volume, unswollen_volume)

print("The free swell index of the soil is:", free_swell_index, "%")