# -*- coding: utf-8 -*-
"""FOUNDATION_UNIT-5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZp2eyT4Fq8X9_5HH6akQYUoFStpOXjq
"""

def get_footing_type(depth, width):
  """Returns the type of footing based on the input value of Depth and Width.

  Args:
    depth: The depth of the footing in meters.
    width: The width of the footing in meters.

  Returns:
    A string representing the type of footing.
  """

  if depth > width:
    # Deep footing
    footing_type = "Deep footing"
  else:
    # Shallow footing
    footing_type = "Shallow footing"

  return footing_type


# Example usage:

depth = 0.8
width = 1.8

footing_type = get_footing_type(depth, width)

print("The type of footing is:", footing_type)